Markup\AddressingBundle\Checker\AddressUnderCheck:
    properties:
        country:
            - Regex:
                pattern: '/[A-Z]{2}/'
    constraints:
        - Markup\AddressingBundle\Validator\PostalCodeConstraint: ~
