language: php

php:
    - 7.1
    - 7.2
    - 7.3
    - 7.4

before_script: composer install --dev --prefer-source

notifications:
  email: "douglas@usemarkup.com"

dist: bionic

script:
  - make analysis
  - make unit

