language: php

php:
    - 5.6
    - 7.0
    - 7.1
    - hhvm

before_script: composer install --dev --prefer-source

notifications:
  email: "douglas@usemarkup.com"

matrix:
   allow_failures:
       - php: 7.1
